import { type TranslationItem } from "@/components/games/TranslationGame";

export const options: TranslationItem[] = [
    { value: '0', level: 1, points: 1, translation: 'zero' },
    { value: '1', level: 1, points: 1, translation: 'one' },
    { value: '2', level: 1, points: 1, translation: 'two' },
    { value: '3', level: 1, points: 1, translation: 'three' },
    { value: '4', level: 1, points: 1, translation: 'four' },
    { value: '5', level: 1, points: 1, translation: 'five' },
    { value: '6', level: 1, points: 1, translation: 'six' },
    { value: '7', level: 1, points: 1, translation: 'seven' },
    { value: '8', level: 1, points: 1, translation: 'eight' },
    { value: '9', level: 1, points: 1, translation: 'nine' },
    { value: '10', level: 2, points: 1, translation: 'ten' },
    { value: '11', level: 2, points: 1, translation: 'eleven' },
    { value: '12', level: 2, points: 1, translation: 'twelve' },
    { value: '13', level: 2, points: 1, translation: 'thirteen' },
    { value: '14', level: 2, points: 1, translation: 'fourteen' },
    { value: '15', level: 2, points: 1, translation: 'fifteen' },
    { value: '16', level: 2, points: 1, translation: 'sixteen' },
    { value: '17', level: 2, points: 1, translation: 'seventeen' },
    { value: '18', level: 2, points: 1, translation: 'eighteen' },
    { value: '19', level: 2, points: 1, translation: 'nineteen' },
    { value: '20', level: 3, points: 1, translation: 'twenty' },
    { value: '21', level: 3, points: 1, translation: 'twenty-one' },
    { value: '22', level: 3, points: 1, translation: 'twenty-two' },
    { value: '23', level: 3, points: 1, translation: 'twenty-three' },
    { value: '24', level: 3, points: 1, translation: 'twenty-four' },
    { value: '25', level: 3, points: 1, translation: 'twenty-five' },
    { value: '26', level: 3, points: 1, translation: 'twenty-six' },
    { value: '27', level: 3, points: 1, translation: 'twenty-seven' },
    { value: '28', level: 3, points: 1, translation: 'twenty-eight' },
    { value: '29', level: 3, points: 1, translation: 'twenty-nine' },
    { value: '30', level: 3, points: 1, translation: 'thirty' },
    { value: '31', level: 3, points: 1, translation: 'thirty-one' },
    { value: '32', level: 3, points: 1, translation: 'thirty-two' },
    { value: '33', level: 3, points: 1, translation: 'thirty-three' },
    { value: '34', level: 3, points: 1, translation: 'thirty-four' },
    { value: '35', level: 3, points: 1, translation: 'thirty-five' },
    { value: '36', level: 3, points: 1, translation: 'thirty-six' },
    { value: '37', level: 3, points: 1, translation: 'thirty-seven' },
    { value: '38', level: 3, points: 1, translation: 'thirty-eight' },
    { value: '39', level: 3, points: 1, translation: 'thirty-nine' },
    { value: '40', level: 3, points: 1, translation: 'forty' },
    { value: '41', level: 3, points: 1, translation: 'forty-one' },
    { value: '42', level: 3, points: 1, translation: 'forty-two' },
    { value: '43', level: 3, points: 1, translation: 'forty-three' },
    { value: '44', level: 3, points: 1, translation: 'forty-four' },
    { value: '45', level: 3, points: 1, translation: 'forty-five' },
    { value: '46', level: 3, points: 1, translation: 'forty-six' },
    { value: '47', level: 3, points: 1, translation: 'forty-seven' },
    { value: '48', level: 3, points: 1, translation: 'forty-eight' },
    { value: '49', level: 3, points: 1, translation: 'forty-nine' },
    { value: '50', level: 3, points: 1, translation: 'fifty' },
    { value: '51', level: 3, points: 1, translation: 'fifty-one' },
    { value: '52', level: 3, points: 1, translation: 'fifty-two' },
    { value: '53', level: 3, points: 1, translation: 'fifty-three' },
    { value: '54', level: 3, points: 1, translation: 'fifty-four' },
    { value: '55', level: 3, points: 1, translation: 'fifty-five' },
    { value: '56', level: 3, points: 1, translation: 'fifty-six' },
    { value: '57', level: 3, points: 1, translation: 'fifty-seven' },
    { value: '58', level: 3, points: 1, translation: 'fifty-eight' },
    { value: '59', level: 3, points: 1, translation: 'fifty-nine' },
    { value: '60', level: 3, points: 1, translation: 'sixty' },
    { value: '61', level: 3, points: 1, translation: 'sixty-one' },
    { value: '62', level: 3, points: 1, translation: 'sixty-two' },
    { value: '63', level: 3, points: 1, translation: 'sixty-three' },
    { value: '64', level: 3, points: 1, translation: 'sixty-four' },
    { value: '65', level: 3, points: 1, translation: 'sixty-five' },
    { value: '66', level: 3, points: 1, translation: 'sixty-six' },
    { value: '67', level: 3, points: 1, translation: 'sixty-seven' },
    { value: '68', level: 3, points: 1, translation: 'sixty-eight' },
    { value: '69', level: 3, points: 1, translation: 'sixty-nine' },
    { value: '70', level: 3, points: 1, translation: 'seventy' },
    { value: '71', level: 3, points: 1, translation: 'seventy-one' },
    { value: '72', level: 3, points: 1, translation: 'seventy-two' },
    { value: '73', level: 3, points: 1, translation: 'seventy-three' },
    { value: '74', level: 3, points: 1, translation: 'seventy-four' },
    { value: '75', level: 3, points: 1, translation: 'seventy-five' },
    { value: '76', level: 3, points: 1, translation: 'seventy-six' },
    { value: '77', level: 3, points: 1, translation: 'seventy-seven' },
    { value: '78', level: 3, points: 1, translation: 'seventy-eight' },
    { value: '79', level: 3, points: 1, translation: 'seventy-nine' },
    { value: '80', level: 3, points: 1, translation: 'eighty' },
    { value: '81', level: 3, points: 1, translation: 'eighty-one' },
    { value: '82', level: 3, points: 1, translation: 'eighty-two' },
    { value: '83', level: 3, points: 1, translation: 'eighty-three' },
    { value: '84', level: 3, points: 1, translation: 'eighty-four' },
    { value: '85', level: 3, points: 1, translation: 'eighty-five' },
    { value: '86', level: 3, points: 1, translation: 'eighty-six' },
    { value: '87', level: 3, points: 1, translation: 'eighty-seven' },
    { value: '88', level: 3, points: 1, translation: 'eighty-eight' },
    { value: '89', level: 3, points: 1, translation: 'eighty-nine' },
    { value: '90', level: 3, points: 1, translation: 'ninety' },
    { value: '91', level: 3, points: 1, translation: 'ninety-one' },
    { value: '92', level: 3, points: 1, translation: 'ninety-two' },
    { value: '93', level: 3, points: 1, translation: 'ninety-three' },
    { value: '94', level: 3, points: 1, translation: 'ninety-four' },
    { value: '95', level: 3, points: 1, translation: 'ninety-five' },
    { value: '96', level: 3, points: 1, translation: 'ninety-six' },
    { value: '97', level: 3, points: 1, translation: 'ninety-seven' },
    { value: '98', level: 3, points: 1, translation: 'ninety-eight' },
    { value: '99', level: 3, points: 1, translation: 'ninety-nine' },
    { value: '100', level: 4, points: 1, translation: 'one hundred' },
    { value: '110', level: 4, points: 1, translation: 'one hundred ten' },
    { value: '120', level: 4, points: 1, translation: 'one hundred twenty' },
    { value: '130', level: 4, points: 1, translation: 'one hundred thirty' },
    { value: '140', level: 4, points: 1, translation: 'one hundred forty' },
    { value: '150', level: 4, points: 1, translation: 'one hundred fifty' },
    { value: '160', level: 4, points: 1, translation: 'one hundred sixty' },
    { value: '170', level: 4, points: 1, translation: 'one hundred seventy' },
    { value: '180', level: 4, points: 1, translation: 'one hundred eighty' },
    { value: '190', level: 4, points: 1, translation: 'one hundred ninety' },
    { value: '200', level: 4, points: 1, translation: 'two hundred' },
    { value: '210', level: 4, points: 1, translation: 'two hundred ten' },
    { value: '220', level: 4, points: 1, translation: 'two hundred twenty' },
    { value: '230', level: 4, points: 1, translation: 'two hundred thirty' },
    { value: '240', level: 4, points: 1, translation: 'two hundred forty' },
    { value: '250', level: 4, points: 1, translation: 'two hundred fifty' },
    { value: '260', level: 4, points: 1, translation: 'two hundred sixty' },
    { value: '270', level: 4, points: 1, translation: 'two hundred seventy' },
    { value: '280', level: 4, points: 1, translation: 'two hundred eighty' },
    { value: '290', level: 4, points: 1, translation: 'two hundred ninety' },
    { value: '300', level: 4, points: 1, translation: 'three hundred' },
    { value: '310', level: 4, points: 1, translation: 'three hundred ten' },
    { value: '320', level: 4, points: 1, translation: 'three hundred twenty' },
    { value: '330', level: 4, points: 1, translation: 'three hundred thirty' },
    { value: '340', level: 4, points: 1, translation: 'three hundred forty' },
    { value: '350', level: 4, points: 1, translation: 'three hundred fifty' },
    { value: '360', level: 4, points: 1, translation: 'three hundred sixty' },
    { value: '370', level: 4, points: 1, translation: 'three hundred seventy' },
    { value: '380', level: 4, points: 1, translation: 'three hundred eighty' },
    { value: '390', level: 4, points: 1, translation: 'three hundred ninety' },
    { value: '400', level: 4, points: 1, translation: 'four hundred' },
    { value: '500', level: 4, points: 1, translation: 'five hundred' },
    { value: '600', level: 4, points: 1, translation: 'six hundred' },
    { value: '700', level: 4, points: 1, translation: 'seven hundred' },
    { value: '800', level: 4, points: 1, translation: 'eight hundred' },
    { value: '900', level: 4, points: 1, translation: 'nine hundred' },
    { value: '1000', level: 4, points: 1, translation: 'one thousand' },
];

export function getRandomOption(): TranslationItem {
    const randomIndex = Math.floor(Math.random() * options.length);
    return options[randomIndex];
}
