version: '3.8'

services:
    geekenglish_postgres:
        image: postgis/postgis:17-3.5
        platform: linux/amd64
        container_name: geekenglish_postgres
        environment:
            POSTGRES_DB: geekenglish_db
            POSTGRES_USER: geekenglish_user
            POSTGRES_PASSWORD: geekenglish_pass
        ports:
            - '5432:5432'
        volumes:
            - ./postgresql:/var/lib/postgresql/data
            - ./database/initdb.d:/docker-entrypoint-initdb.d

    geekenglish_redis:
        image: redis:6
        container_name: geekenglish_redis
        ports:
            - '6379:6379'
